// <auto-generated />
using System;
using Gezify.Api.Data;
using Gezify.Api.Data.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gezify.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405152040_AddCoreDomainSchema")]
    partial class AddCoreDomainSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "expense_category", new[] { "food", "accommodation", "transfer", "souvenir", "activity" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "invitation_status", new[] { "pending", "accepted", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "travel_status", new[] { "active", "all_finished", "settled" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gezify.Api.Data.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountTry")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_try");

                    b.Property<ExpenseCategory>("Category")
                        .HasColumnType("expense_category")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTimeOffset>("ExpenseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expense_date");

                    b.Property<string>("Location")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("location");

                    b.Property<Guid?>("PaidById")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_id");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("PaidById");

                    b.HasIndex("TravelId", "ExpenseDate");

                    b.HasIndex("TravelId", "PaidById");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.FinishedAck", b =>
                {
                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TravelId", "UserId");

                    b.HasIndex("TravelId");

                    b.HasIndex("UserId");

                    b.ToTable("finished_acks", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<InvitationStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("invitation_status")
                        .HasDefaultValue(InvitationStatus.Pending)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("token");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitedById");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TravelId", "Status");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.SettlementTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountTry")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_try");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("TravelId");

                    b.ToTable("settlement_transfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_settlement_transfers_distinct_users", "from_user_id <> to_user_id");
                        });
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Travel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<TravelStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("travel_status")
                        .HasDefaultValue(TravelStatus.Active)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Status");

                    b.ToTable("travels", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.TravelMember", b =>
                {
                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TravelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("travel_members", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("google_id");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Expense", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.User", "AddedBy")
                        .WithMany("ExpensesAdded")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.User", "PaidBy")
                        .WithMany("ExpensesPaid")
                        .HasForeignKey("PaidById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gezify.Api.Data.Entities.Travel", "Travel")
                        .WithMany("Expenses")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("PaidBy");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.FinishedAck", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.Travel", "Travel")
                        .WithMany("FinishedAcks")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.User", "User")
                        .WithMany("FinishedAcks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Travel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Invitation", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.User", "InvitedBy")
                        .WithMany("InvitationsSent")
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.Travel", "Travel")
                        .WithMany("Invitations")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedBy");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.SettlementTransfer", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.User", "FromUser")
                        .WithMany("SettlementTransfersFrom")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.User", "ToUser")
                        .WithMany("SettlementTransfersTo")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.Travel", "Travel")
                        .WithMany("SettlementTransfers")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Travel", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.User", "Creator")
                        .WithMany("TravelsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.TravelMember", b =>
                {
                    b.HasOne("Gezify.Api.Data.Entities.Travel", "Travel")
                        .WithMany("Members")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gezify.Api.Data.Entities.User", "User")
                        .WithMany("TravelMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Travel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.Travel", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("FinishedAcks");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("SettlementTransfers");
                });

            modelBuilder.Entity("Gezify.Api.Data.Entities.User", b =>
                {
                    b.Navigation("ExpensesAdded");

                    b.Navigation("ExpensesPaid");

                    b.Navigation("FinishedAcks");

                    b.Navigation("InvitationsSent");

                    b.Navigation("SettlementTransfersFrom");

                    b.Navigation("SettlementTransfersTo");

                    b.Navigation("TravelMemberships");

                    b.Navigation("TravelsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
